python .\gen_module_block.py -d -t ct_ifu_top -i x_ct_ifu_pcgen ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\cpu\rtl\cpu_cfig.h ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_addrgen.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_bht_pre_array.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_bht_sel_array.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_bht.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_btb_data_array.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_btb_tag_array.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_btb.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_debug.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_decd_normal.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ibctrl.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ibdp.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ibuf_entry.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ibuf.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_icache_data_array0.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_icache_data_array1.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_icache_if.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_icache_predecd_array0.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_icache_predecd_array1.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_icache_tag_array.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ifctrl.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ifdp.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ind_btb_array.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ind_btb.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ipb.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ipctrl.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ipdecode.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ipdp.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_l0_btb_entry.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_l0_btb.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_l1_refill.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_lbuf_entry.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_lbuf.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_pcfifo_if.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_pcgen.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_precode.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_ras.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_sfp_entry.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_sfp.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_top.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_ifu_vector.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_spsram_128x16.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_spsram_256x23.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_spsram_256x59.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_spsram_512x22.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_spsram_512x44.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_spsram_512x59.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_spsram_1024x59.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_spsram_1024x64.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_spsram_2048x32_split.v ^
F:\Notebooks\openc910\C910_RTL_FACTORY\gen_rtl\ifu\rtl\ct_spsram_2048x59.v